CREATE TABLE SUBWAY(
IDSubway		INT				CONSTRAINT PK_Metro_IDMetro PRIMARY KEY IDENTITY(1,1),
NameSubway		NVARCHAR(15)	not null								DEFAULT 'Nameless');

GO

CREATE TABLE LINE(
IDLine			INT				CONSTRAINT PK_Line_IDLine		PRIMARY KEY		IDENTITY(1,1),
NameLine		NVARCHAR(20)	not null										DEFAULT 'Nameless',
LineKey			NVARCHAR(1)		not null										DEFAULT 'U',
IDSubway		INT				CONSTRAINT FK_Metro_IDSubway	FOREIGN KEY		REFERENCES SUBWAY(IDSubway));

GO

CREATE TABLE STATION(
IDStation	INT				CONSTRAINT PK_Station_IDStation PRIMARY KEY IDENTITY(1,1),
NameStation NVARCHAR(20)	not null									DEFAULT 'Nameless');

GO

CREATE TABLE LINE_STATION(
IDLineStation	INT CONSTRAINT PK_lINESTATION_IDLineStation	PRIMARY KEY,
IDLine			INT,
IDStation		INT,
Position		INT,
				CONSTRAINT FK_lINE_IDline		FOREIGN KEY (IDline)			REFERENCES LINE(IDLine),
				CONSTRAINT FK_STATION_IDStation FOREIGN KEY (IDStation)			REFERENCES STATION(IDStation));

GO

CREATE TABLE PERMISSION(
IDPermission INT CONSTRAINT PK_PERMISSION_IDPermission		PRIMARY KEY IDENTITY(1,1),
TypePermission NVARCHAR(20));

CREATE TABLE PERSON(
IDPerson		INT				CONSTRAINT PK_PERSON_IDPerson				PRIMARY KEY IDENTITY(1,1),
UserName		NVARCHAR(50)	CONSTRAINT UK_PERSON_UserName				UNIQUE,
Permission		INT				CONSTRAINT FK_PERMISSION_IDPermission		FOREIGN KEY (Permission)				
								REFERENCES PERMISSION (IDPermission)		not null							DEFAULT 2,
Active			BIT				not null									DEFAULT 1,
HashPassword	NVARCHAR(50)	CONSTRAINT UK_PERSON_HashPassword			UNIQUE,
Salt			NVARCHAR(10)	CONSTRAINT UK_PERSON_Salt					UNIQUE);

GO

CREATE TABLE TRIP(
IDTrip		INT				CONSTRAINT PK_TRIP_IDTrip			PRIMARY KEY				IDENTITY (1,1),
IDPerson	INT				CONSTRAINT FK_PERSON_IDPerson		FOREIGN KEY (IDPerson)	REFERENCES PERSON (IDPerson),
Departure	INT not null	CONSTRAINT FK_Station_Departure		FOREIGN KEY (Departure) REFERENCES Station (IDStation),
Arrival		INT not null	CONSTRAINT FK_Station_Arrival		FOREIGN KEY (Arrival)	REFERENCES Station (IDStation));

GO

CREATE TABLE TRIP_LINESTATION(
IDLineStation			INT,
IDTrip					INT,
StationRoutePosition	INT,
						CONSTRAINT PK_STATION_COURSE_ID				PRIMARY KEY (IDTrip, IDLineStation),
						CONSTRAINT FK_LINE_STATION_IDLineStation	FOREIGN KEY (IDLineStation)				REFERENCES LINE_STATION (IDLineStation),
						CONSTRAINT FK_COURSE_Trip					FOREIGN KEY (IDTrip)					REFERENCES TRIP (IDTrip));
